version: "3"

services:
  pspdfkit:
    image: "springboot-activemq-producer:0.0.1-SNAPSHOT"
    expose:
      - "8082"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pspdfkit
    ports:
      - "8082:4000"